/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javatraining2;

import java.sql.Connection;


/**
 *
 * @author radhika
 */
public class HOME1 extends javax.swing.JPanel {

    /**
     * Creates new form HOME1
     */
    public HOME1() {
        initComponents();
    }
   public HOME1(login e)
   {
       this();
       this.e=e;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1095, 730));
        setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javatraining2/9.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        add(jLabel4);
        jLabel4.setBounds(400, 200, 280, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javatraining2/8.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(730, 420, 280, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javatraining2/7.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(130, 420, 270, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javatraining2/recycled_texture_background_by_sandeep_m_d6aeau9_by_mintygumball-d87zctp.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         Connection c = MSconnect.connecrDb();
         login t=this.e;
         t.tab2.addTab("STUDENT", new student());
            t.tab2.setEnabledAt(2,true);
            t.validate();
        
       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         Connection c = MSconnect.connecrDb();
         login t=this.e;
         t.tab2.addTab("MID DAY MEAL", new mdm());
            t.tab2.setEnabledAt(2,true);
            t.validate();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         Connection c = MSconnect.connecrDb();
         login t=this.e;
         t.tab2.addTab("ANNUAL", new annual());
            t.tab2.setEnabledAt(2,true);
            t.validate();
        
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    private login e;
}
